<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.f9Yb30F' shared service.

return $this->privates['.service_locator.f9Yb30F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'manager' => array('services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true),
    'reservation' => array('privates', '.errored..service_locator.f9Yb30F.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.f9Yb30F": it references class "App\\Entity\\Reservation" but no such service exists.'),
    'security' => array('privates', 'security.helper', 'getSecurity_HelperService.php', true),
));
