<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB3yvxls\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB3yvxls/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB3yvxls.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB3yvxls\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerB3yvxls\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'B3yvxls',
    'container.build_id' => '34fff41a',
    'container.build_time' => 1559824456,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerB3yvxls');
